# Generated by Django 4.1.2 on 2022-11-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracterisca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100, verbose_name='Matricula')),
                ('tipo', models.CharField(choices=[('Nav', 'Navio'), ('Avi', 'Avião'), ('Cam', 'Caminhão'), ('Oni', 'Onibus'), ('Van', 'Van'), ('Car', 'Carro'), ('Mot', 'Moto'), ('Bic', 'Bicicleta')], max_length=3)),
                ('ano', models.DateField()),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de veículos')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Matricula')),
                ('tipo_contrato', models.CharField(choices=[('cole', 'Coleta'), ('entr', 'Entrega'), ('desp', 'Despachar')], max_length=4)),
                ('faturado', models.CharField(choices=[('pago', 'Pago'), ('npag', 'Não Pagou'), ('rece', 'A receber')], max_length=4)),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de veículos')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.tipocontrato')),
            ],
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.cliente')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.tipocontrato')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.veiculo')),
            ],
        ),
    ]
