# Generated by Django 4.1.2 on 2022-11-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logapp.cliente'),
        ),
        migrations.AlterField(
            model_name='agendar',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logapp.tipocontrato'),
        ),
        migrations.AlterField(
            model_name='agendar',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logapp.veiculo'),
        ),
    ]
