# Generated by Django 4.1.2 on 2022-11-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_alter_agendar_cliente_alter_agendar_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='caracteristica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.caracterisca'),
        ),
    ]
