# Generated by Django 4.1.2 on 2022-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_veiculo_caracteristica'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='orcamento',
            field=models.CharField(max_length=100, null=True, verbose_name='Orçamento'),
        ),
    ]
